services:
  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - backend

  django:
    build: .
    container_name: django
    command: sh -c "python manage.py migrate && python manage.py makemigrations && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/spa_app/static/
      - media_volume:/usr/src/app/media/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    ports:
      - "8000:8000"

  mkcert:
    build:
      context: .
      dockerfile: Dockerfile.mkcert
    volumes:
      - certs:/certs
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/src/app/media/
      - certs:/certs
    depends_on:
      - django
      - mkcert
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:

networks:
  backend:
    driver: bridge
